apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduller-auth
spec:
  replicas: 5
  selector:
    matchLabels:
      app: scheduller-auth
  template:
    metadata:
      labels:
        app: scheduller-auth
    spec:
      containers:
        - name: app
          image: lmtp/scheduler-auth:latest
          ports:
            - containerPort: 2002
          volumeMounts:
            - name: uploads-storage
              mountPath: /uploads 
          envFrom:
            - configMapRef:
                name: env-config-scheduler
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: scheduler-auth-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: scheduller-auth-service
spec:
  selector:
    app: scheduller-auth
  ports:
    - protocol: TCP
      port: 2002
      targetPort: 2002
  type: LoadBalancer